vatACARS/plugin

vatACARS/Components/DispatchWindow.cs
vatACARS/Components/EditorWindow.cs
vatACARS/Components/LogonConsentWindow.Designer.cs
vatACARS/Components/LogonConsentWindow.cs
vatACARS/Components/LogonConsentWindow.resx
vatACARS/Components/PDCWindow.Designer.cs
vatACARS/Components/PDCWindow.cs
vatACARS/Lib/Tranceiver.cs
vatACARS/Lib/UpdateClient.cs
vatACARS/Lib/VersionChecker.cs
vatACARS/Util/HoppiesInterface.cs
vatACARS/vatACARS.cs
vatACARS/vatACARS.csproj

New Stuffs (TBD)

---

vatACARS/Lib/Tranceiver.cs

Feat: Message Timer

---

vatACARS/Components/PDCWindow.Designer.cs

update font sizes for a better UI look and uniform feel.

UPDATE: Update PDC Window Font Size

---

vatACARS/Components/EditorWindow.cs

FIXED: Editor Window Crashing Vatsys on new line added

---

vatACARS/Components/SetupWindow.Designer.cs
vatACARS/Components/SetupWindow.cs
vatACARS/Properties/Settings.Designer.cs
vatACARS/Properties/Settings.settings
vatACARS/Util/AudioInterface.cs
vatACARS/app.config

Feat: Volume Controls

---

vatACARS/Components/EditorWindow.cs

FEAT: added message phrasing to editor window

---

vatACARS/Components/SetupWindow.Designer.cs
vatACARS/Components/SetupWindow.cs
vatACARS/Lib/Tranceiver.cs
vatACARS/Properties/Settings.Designer.cs
vatACARS/Properties/Settings.settings
vatACARS/app.config

added: finished msg timeout fixes #60 
fixed: volume setting not saving

Feat: Message Timeout , Fix: Volume Saving

---

vatACARS/Components/DispatchWindow.cs
vatACARS/Components/ErrorWindow.Designer.cs
vatACARS/Components/ErrorWindow.cs
vatACARS/Components/ErrorWindow.resx
vatACARS/Components/PDCWindow.cs
vatACARS/Util/ErrorHandler.cs
vatACARS/Util/HoppiesInterface.cs
vatACARS/vatACARS.csproj

added error window and error handler closes #78

Feat ErrorWindow

---

vatACARS/Components/QuickFillWindow.Designer.cs
vatACARS/Components/QuickFillWindow.cs

Added horizontal scrolling to quickfill window.
fixes #43

Feat QuickFIllWindow Scrolling

---

vatACARS/Components/PDCWindow.Designer.cs
vatACARS/Components/PDCWindow.cs
vatACARS/Components/PDCWindow.resx

added: Frequency dropdown to the PDC window
resolves #82

Feat: Freq DropDown

---

vatACARS/Components/EditorWindow.cs
vatACARS/Components/QuickFillWindow.cs

added: loading route for quick-fill (position) messages

Feat: QuickFillRoute

---

vatACARS/Components/DispatchWindow.cs
vatACARS/Components/EditorWindow.cs
vatACARS/Components/QuickFillWindow.cs

fixed a few quickfillwindow bugs and a editor window bug

---

vatACARS/vatACARS.cs

fixed crash when clicking @ REQ label on ground aircraft.

---

vatACARS/Components/DispatchWindow.cs
vatACARS/Components/EditorWindow.Designer.cs
vatACARS/Components/EditorWindow.cs
vatACARS/Lib/Transceiver.cs
vatACARS/Util/VatACARSInterface.cs
vatACARS/vatACARS.cs

fixes #114 
fixes #111
Adds Editor Window ESCAPE,RESTORE,SUSPEND buttons functions.

Bug Fixes / Editor Window Updates

---

vatACARS/Components/PDCWindow.cs

Fixed PDC not containing freqs

---

vatACARS/Components/DispatchWindow.cs
vatACARS/Components/EditorWindow.cs
vatACARS/Components/HistoryWindow.Designer.cs
vatACARS/Components/HistoryWindow.cs
vatACARS/Components/HistoryWindow.resx
vatACARS/Components/QuickFillWindow.Designer.cs
vatACARS/Components/QuickFillWindow.cs
vatACARS/Lib/Transceiver.cs
vatACARS/vatACARS.cs
vatACARS/vatACARS.csproj

also Removed redundant mouse wheel event handler and enhanced UNIT NAME , FREQUENCY selection logic

Added History Window and overhauled Quick Fill Window.

---

vatACARS/Components/EditorWindow.cs
vatACARS/Components/PDCWindow.Designer.cs
vatACARS/Components/PDCWindow.cs

- EditorWindow.cs: Disable buttons and set title for specific message states; call ShowGroupBasedOnMessageContent.
- PDCWindow.Designer.cs: Add event handler for dd_freq2 SelectedIndexChanged.
- PDCWindow.cs: Clean up using directives; modify addSentCPDLCMessage to decrement MessageId; set networkPilotFDR.PDCSent to true; update CutStringAndAppendT to replace backslashes with spaces; add event handlers for dd_freq and dd_freq2 to remove non-numeric characters.

Enhance UI and event handling in Editor and PDC windows

---

vatACARS/Components/DispatchWindow.cs

Fixed #135 Aircraft marked as standby means there message disappears

Fixed #135 Aircraft marked as standby means there message disappears

---

vatACARS/Components/EditorWindow.Designer.cs
vatACARS/Components/EditorWindow.cs
vatACARS/Components/QuickFillWindow.Designer.cs

Significant modifications to EditorWindow.Designer.cs:
- Renamed and added multiple UI components (InsetPanel, TextLabel, GenericButton).
- Replaced old components with new ones (insetPanel_0 to insetPanel_4, lbl_response_0 to lbl_response_4, btn_messageScroller_0 to btn_messageScroller_4).
- Adjusted form properties (ClientSize, MinimumSize, Anchor properties).
- Updated SuspendLayout and ResumeLayout calls.
- Set Resizeable to false and SizeGripStyle to Hide.
- Updated form Text property to "ACARS Editor".
Refactored response handling:
- Changed responseIndex to an instance variable.
- Added new instance variables for managing multiple response labels and buttons.
- Added initialization methods for scroller buttons and response labels.
- Replaced lbl_response and btn_messageScroller …

Refactor EditorWindow UI and response handling

---

vatACARS/Components/DispatchWindow.cs
vatACARS/Components/EditorWindow.cs
vatACARS/Components/HistoryWindow.cs
vatACARS/Components/PDCWindow.cs
vatACARS/Components/QuickFillWindow.cs
vatACARS/Components/SetupWindow.cs
vatACARS/vatACARS.cs

Reordered and re-added methods in DispatchWindow.cs, EditorWindow.cs, PDCWindow.cs, and SetupWindow.cs for better organization. Removed unused using directives in HistoryWindow.cs and SetupWindow.cs. Fixed visual bug on EditorWindow.cs

Refactor and reorganize methods across multiple files

---

vatACARS/Components/EditorWindow.cs
vatACARS/Components/Popup.Designer.cs
vatACARS/Components/Popup.cs
vatACARS/Components/Popup.resx
vatACARS/Lib/Transceiver.cs
vatACARS/vatACARS.csproj

Introduced a new PopupWindow component to display confirmation dialogs for the DIRECT intent type. Updated EditorWindow.cs to handle the new intent type and removed a duplicate detection string. Modified Transceiver.cs to show the popup window for DIRECT intents. Added PopupWindow class files to the project and updated vatACARS.csproj accordingly.

Add PopupWindow for DIRECT intent handling
